version: '3.8'
name: "grpc-fastapi"
services:
  orders:
    container_name: orders-api
    image: python3-grpc
    volumes:
      - "./app:/usr/src/app"
    environment:
      - GRPC_HOST_LOCAL=0.0.0.0
      - GRPC_PORT=50091
      - SERVICE_PORT=1111
      - SERVICE_HOST_LOCAL=0.0.0.0
    command: "python main.py"

